return {
  {
    type = "settings",
    name = "mydebug",
    data = {
      Joystick = {onConsole = true},
      JoystickConfig = {onConsole = false},
      JoystickTracker = {onConsole = true},
    },
  },
  {
    type = "data",
    name = "gamepad_layout",
    datafile = "modules/joystickconfig/maps/gamepad_layout.lua",
  },
  {
    type = "data",
    name = "snes_layout",
    datafile = "modules/joystickconfig/maps/snes_layout.lua",
  },
  {
    type = "data",
    name = "gamepad_pro_layout",
    datafile = "modules/joystickconfig/maps/gamepad_pro_layout.lua",
  },
  {
    type = "data",
    name = "generic_dualstick_layout",
    datafile = "modules/joystickconfig/maps/generic_dualstick_layout.lua",
  },
  {
    type = "data",
    name = "joysticks",
    data = {
      ["Generic   USB  Joystick  "] = {
        controlMap = {
          numAxes = 5,
          numButtons = 12,
          axes = {leftx = 1, lefty = 2, unknown = 3, rightx = 4, righty = 5},
          buttons = {
            face1 = 1,
            face2 = 2,
            face3 = 3,
            face4 = 4,
            l2 = 5,
            r2 = 6,
            l1 = 7,
            r1 = 8,
            select = 9,
            start = 10,
            l3 = 11,
            r3 = 12,
          },
        },
        viewLayout = "generic_dualstick_layout",
      },
      ["GamePad Pro USB "] = {
        controlMap = {
          numAxes = 2,
          numButtons = 10,
          axes = {leftx = 1, lefty = 2},
          buttons = {
            face1 = 4,
            face2 = 3,
            face3 = 2,
            face4 = 1,
            l2 = 5,
            r2 = 6,
            l1 = 7,
            r1 = 8,
            select = 9,
            start = 10,
          },
        },
        viewLayout = "gamepad_pro_layout",
      },
      ["DEFAULT"] = {
        controlMap = {
          numAxes = 5,
          numButtons = 12,
          axes = {leftx = 1, lefty = 2, unknown = 3, rightx = 4, righty = 5},
          buttons = {
            face1 = 1,
            face2 = 2,
            face3 = 3,
            face4 = 4,
            l2 = 5,
            r2 = 6,
            l1 = 7,
            r1 = 8,
            select = 9,
            start = 10,
            l3 = 11,
            r3 = 12,
          },
        },
        viewLayout = "generic_dualstick_layout",
      },
    },
  },
}
